# vrc2webp default configuration file

# CPU priorities of processes: above_normal, normal, below_normal, idle
# Using lower priorities by default to not interfere with other running software.
# It's not possible to set realtime or high priorities for safety/sanity reasons.
own-priority-cpu: below_normal
recoders-priority-cpu: idle

# IO priorities of processes: normal, low, very_low
# Using lower priorities by default to not interfere with other running software.
# It's not possible to set high IO priority for safety/sanity reasons.
own-priority-io: low
recoders-priority-io: very_low

# Where to watch files to recode to WEBP.
# Windows environment %VARIABLES% are supported.
# \\REMOTE\Share\paths are also supported, but good network connection required to prevent issues.
watch-paths:
  - '%USERPROFILE%\Pictures\VRChat\'
  - '%USERPROFILE%\Pictures\ChilloutVR\'

# How to process given watch paths:
# - observe - detect and recode new suitable files, run program indefinitely.
# - scan - scan and recode all suitable files, then exit program.
# - both - scan and recode all suitable files, then observe. (Default)
# You can send CTRL+C event / SIGBREAK signal at any time to ask program to stop.
# It may take few seconds to terminate subprocesses, clean up temp files and stop gracefully.
watch-mode: both

# Look for files in sub-folders.
# recursive: true
# NOT IMPLEMENTED YET; ALWAYS RECURSIVE

# Number of seconds to wait before trying to process new observed files.
# It's hard to detect if file just stored or being written right now. Scanning every handle for every file is overkill.
# So vrc2webp just wait this given time and if file size is changed, then wait again and again in loop.
new-files-timeout: 5.0

# Extensions of original files to convert to WEBP.
# JPEGs are also included if you used mods for JPEG screenshots before.
# But recoding JPEGs usually does not give much better compression.
# You may exclude it to save time if you have tons of JPEGs.
# Note: extensions .tmp.jpg, .tmp.png, ... are used internally and ignored.
# You may see those .tmp files during recoding, it will be rolled back automatically when complete or cancelled.
file-extensions: [ .png, .jpg, .jpeg ]

# Change naming format of VRChat screenshots. Ex:
# VRChat_3840x2160_2021-11-10_19-21-40.183.webp -> VRChat_2021-11-10_19-21-40.183_3840x2160.webp
# Most software will sort files in correct order if date is first part of the name.
vrc-swap-resolution-and-time: true

# How many recode processes (cwebp.exe) to run in parallel.
# if 0 or negative - will choose automatically number of logical cores on your CPU.
max-parallel-recodes: -1

# Try update modification time of recoded WEBP files to be the same as originals.
update-mtime: true

# Where to delete original files:
# - keep - do not delete anything, keep original file with converted.
# - trash - delete to system Recycle Bin, keeps space on disk used, but possible to restore. (Default)
# - unlink - delete file permanently from file system.
delete-mode: trash
